#include "ofxCIConstants.h"

// CICategoryBlur
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BOX_BLUR = "CIBoxBlur";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DISC_BLUR = "CIDiscBlur";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GAUSSIAN_BLUR = "CIGaussianBlur";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MEDIAN_FILTER = "CIMedianFilter";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MOTION_BLUR = "CIMotionBlur";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_NOISE_REDUCTION = "CINoiseReduction";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_ZOOM_BLUR = "CIZoomBlur";

// CICategoryColorAdjustment
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_CLAMP = "CIColorClamp";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_CONTROLS = "CIColorControls";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_MATRIX = "CIColorMatrix";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_POLYNOMIAL = "CIColorPolynomial";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_EXPOSURE_ADJUST = "CIExposureAdjust";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GAMMA_ADJUST = "CIGammaAdjust";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HUE_ADJUST = "CIHueAdjust";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LINEAR_TO_SRGB_TONE_CURVE = "CILinearToSRGBToneCurve";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SRGB_TONE_CURVE_TO_LINEAR = "CISRGBToneCurveToLinear";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TEMPERATURE_AND_TINT = "CITemperatureAndTint";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TONE_CURVE = "CIToneCurve";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_VIBRANCE = "CIVibrance";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_WHITE_POINT_ADJUST = "CIWhitePointAdjust";

// CICategoryColorEffect
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_CROSS_POLYNOMIAL = "CIColorCrossPolynomial";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_CUBE = "CIColorCube";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_CUBE_WITH_COLOR_SPACE = "CIColorCubeWithColorSpace";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_INVERT = "CIColorInvert";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_MAP = "CIColorMap";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_MONOCHROME = "CIColorMonochrome";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_POSTERIZE = "CIColorPosterize";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_FALSE_COLOR = "CIFalseColor";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MASK_TO_ALPHA = "CIMaskToAlpha";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MAXIMUM_COMPONENT = "CIMaximumComponent";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MINIMUM_COMPONENT = "CIMinimumComponent";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_CHROME = "CIPhotoEffectChrome";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_FADE = "CIPhotoEffectFade";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_INSTANT = "CIPhotoEffectInstant";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_MONO = "CIPhotoEffectMono";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_NOIR = "CIPhotoEffectNoir";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_PROCESS = "CIPhotoEffectProcess";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_TONAL = "CIPhotoEffectTonal";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PHOTO_EFFECT_TRANSFER = "CIPhotoEffectTransfer";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SEPIA_TONE = "CISepiaTone";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_VIGNETTE = "CIVignette";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_VIGNETTE_EFFECT = "CIVignetteEffect";

// CICategoryCompositeOperation
const OFX_FILTER_TYPE OFX_FILTER_TYPE_ADDITION_COMPOSITING = "CIAdditionCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_BLEND_MODE = "CIColorBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_BURN_BLEND_MODE = "CIColorBurnBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLOR_DODGE_BLEND_MODE = "CIColorDodgeBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DARKEN_BLEND_MODE = "CIDarkenBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DIFFERENCE_BLEND_MODE = "CIDifferenceBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_EXCLUSION_BLEND_MODE = "CIExclusionBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HARD_LIGHT_BLEND_MODE = "CIHardLightBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HUE_BLEND_MODE = "CIHueBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LIGHTEN_BLEND_MODE = "CILightenBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LUMINOSITY_BLEND_MODE = "CILuminosityBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MAXIMUM_COMPOSITING = "CIMaximumCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MINIMUM_COMPOSITING = "CIMinimumCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MULTIPLY_BLEND_MODE = "CIMultiplyBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MULTIPLY_COMPOSITING = "CIMultiplyCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_OVERLAY_BLEND_MODE = "CIOverlayBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SATURATION_BLEND_MODE = "CISaturationBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SCREEN_BLEND_MODE = "CIScreenBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SOFT_LIGHT_BLEND_MODE = "CISoftLightBlendMode";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SOURCE_ATOP_COMPOSITING = "CISourceAtopCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SOURCE_IN_COMPOSITING = "CISourceInCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SOURCE_OUT_COMPOSITING = "CISourceOutCompositing";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SOURCE_OVER_COMPOSITING = "CISourceOverCompositing";

// CICategoryDistortionEffect
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BUMP_DISTORTION = "CIBumpDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BUMP_DISTORTION_LINEAR = "CIBumpDistortionLinear";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CIRCLE_SPLASH_DISTORTION = "CICircleSplashDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CIRCULAR_WRAP = "CICircularWrap";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DROSTE = "CIDroste";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DISPLACEMENT_DISTORTION = "CIDisplacementDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GLASS_DISTORTION = "CIGlassDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GLASS_LOZENGE = "CIGlassLozenge";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HOLE_DISTORTION = "CIHoleDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LIGHT_TUNNEL = "CILightTunnel";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PINCH_DISTORTION = "CIPinchDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_STRETCH_CROP = "CIStretchCrop";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TORUS_LENS_DISTORTION = "CITorusLensDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TWIRL_DISTORTION = "CITwirlDistortion";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_VORTEX_DISTORTION = "CIVortexDistortion";

// CICategoryGenerator
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CHECKERBOARD_GENERATOR = "CICheckerboardGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONSTANT_COLOR_GENERATOR = "CIConstantColorGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LENTICULAR_HALO_GENERATOR = "CILenticularHaloGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_QR_CODE_GENERATOR = "CIQRCodeGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_RANDOM_GENERATOR = "CIRandomGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_STAR_SHINE_GENERATOR = "CIStarShineGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_STRIPES_GENERATOR = "CIStripesGenerator";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SUNBEAMS_GENERATOR = "CISunbeamsGenerator";

// CICategoryGeometryAdjustment
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AFFINE_TRANSFORM = "CIAffineTransform";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CROP = "CICrop";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LANCZOS_SCALE_TRANSFORM = "CILanczosScaleTransform";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PERSPECTIVE_TRANSFORM = "CIPerspectiveTransform";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PERSPECTIVE_TRANSFORM_WITH_EXTENT = "CIPerspectiveTransformWithExtent";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_STRAIGHTEN_FILTER = "CIStraightenFilter";

// CICategoryGradient
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GAUSSIAN_GRADIENT = "CIGaussianGradient";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LINEAR_GRADIENT = "CILinearGradient";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_RADIAL_GRADIENT = "CIRadialGradient";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SMOOTH_LINEAR_GRADIENT = "CISmoothLinearGradient";

// CICategoryHalftoneEffect
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CIRCULAR_SCREEN = "CICircularScreen";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CMYK_HALFTONE = "CICMYKHalftone";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DOT_SCREEN = "CIDotScreen";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HATCHED_SCREEN = "CIHatchedScreen";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LINE_SCREEN = "CILineScreen";

// CICategoryReduction
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_AVERAGE = "CIAreaAverage";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_HISTOGRAM = "CIAreaHistogram";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_ROW_AVERAGE = "CIRowAverage";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COLUMN_AVERAGE = "CIColumnAverage";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HISTOGRAM_DISPLAY_FILTER = "CIHistogramDisplayFilter";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_MAXIMUM = "CIAreaMaximum";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_MINIMUM = "CIAreaMinimum";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_MAXIMUM_ALPHA = "CIAreaMaximumAlpha";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AREA_MINIMUM_ALPHA = "CIAreaMinimumAlpha";

// CICategorySharpen
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SHARPEN_LUMINANCE = "CISharpenLuminance";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_UNSHARP_MASK = "CIUnsharpMask";

// CICategoryStylize
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BLEND_WITH_ALPHA_MASK = "CIBlendWithAlphaMask";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BLEND_WITH_MASK = "CIBlendWithMask";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BLOOM = "CIBloom";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COMIC_EFFECT = "CIComicEffect";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONVOLUTION3X3 = "CIConvolution3X3";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONVOLUTION5X5 = "CIConvolution5X5";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONVOLUTION7X7 = "CIConvolution7X7";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONVOLUTION9_HORIZONTAL = "CIConvolution9Horizontal";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CONVOLUTION9_VERTICAL = "CIConvolution9Vertical";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_CRYSTALLIZE = "CICrystallize";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DEPTH_OF_FIELD = "CIDepthOfField";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_EDGES = "CIEdges";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_EDGE_WORK = "CIEdgeWork";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GLOOM = "CIGloom";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HEIGHT_FIELD_FROM_MASK = "CIHeightFieldFromMask";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HEXAGONAL_PIXELLATE = "CIHexagonalPixellate";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_HIGHLIGHT_SHADOW_ADJUST = "CIHighlightShadowAdjust";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_LINE_OVERLAY = "CILineOverlay";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PIXELLATE = "CIPixellate";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_POINTILLIZE = "CIPointillize";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SHADED_MATERIAL = "CIShadedMaterial";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SPOT_COLOR = "CISpotColor";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SPOT_LIGHT = "CISpotLight";

// CICategoryTileEffect
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AFFINE_CLAMP = "CIAffineClamp";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_AFFINE_TILE = "CIAffineTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_EIGHTFOLD_REFLECTED_TILE = "CIEightfoldReflectedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_FOURFOLD_REFLECTED_TILE = "CIFourfoldReflectedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_FOURFOLD_ROTATED_TILE = "CIFourfoldRotatedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_FOURFOLD_TRANSLATED_TILE = "CIFourfoldTranslatedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_GLIDE_REFLECTED_TILE = "CIGlideReflectedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_KALEIDOSCOPE = "CIKaleidoscope";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_OP_TILE = "CIOpTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PARALLELOGRAM_TILE = "CIParallelogramTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PERSPECTIVE_TILE = "CIPerspectiveTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SIXFOLD_REFLECTED_TILE = "CISixfoldReflectedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SIXFOLD_ROTATED_TILE = "CISixfoldRotatedTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TRIANGLE_KALEIDOSCOPE = "CITriangleKaleidoscope";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TRIANGLE_TILE = "CITriangleTile";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_TWELVEFOLD_REFLECTED_TILE = "CITwelvefoldReflectedTile";

// CICategoryTransition
const OFX_FILTER_TYPE OFX_FILTER_TYPE_BARS_SWIPE_TRANSITION = "CIBarsSwipeTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_COPY_MACHINE_TRANSITION = "CICopyMachineTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DISINTEGRATE_WITH_MASK_TRANSITION = "CIDisintegrateWithMaskTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_DISSOLVE_TRANSITION = "CIDissolveTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_FLASH_TRANSITION = "CIFlashTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_MOD_TRANSITION = "CIModTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PAGE_CURL_TRANSITION = "CIPageCurlTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_PAGE_CURL_WITH_SHADOW_TRANSITION = "CIPageCurlWithShadowTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_RIPPLE_TRANSITION = "CIRippleTransition";
const OFX_FILTER_TYPE OFX_FILTER_TYPE_SWIPE_TRANSITION = "CISwipeTransition";
